stages:
- name: yarn install & build
  steps:
  - runScriptConfig:
      image: 192.168.144.144/base/node:10.13.0-alpine-vue
      shellScript: |-
        yarn install && yarn build
- name: docker build & publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: b2b/antd-pro-vue:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.144.144
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_MIRROR: https://mrpxuz76.mirror.aliyuncs.com
- name: deploy workload
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
